FROM nginx:1.27.2

RUN apt-get update && apt-get -y upgrade

RUN groupadd -r ateniacl && useradd -r -g ateniacl ateniacl
RUN chown -R ateniacl:ateniacl /usr/share/nginx/html
USER ateniacl

CMD ["bash", "-c", "echo Hello from appuser!"]