FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl vim git

RUN echo "Inicio de script" && \
    echo "Ejecutando tarea 1" && \
    echo "Ejecutando tarea 2" && \
    echo "Script finalizado."